#pragma once

#include "NativeGameplayTags.h"

namespace HeroGameplayTags
{
    /** Input Tags **/
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttackAxe);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttackAxe);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwitchTarget);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SpecialWeaponAbility_Light);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SpecialWeaponAbility_Heavy);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_PickUp_Items);

    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld_Block);

    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable_TargetLock);

    /** Player tags **/
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Roll);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Block);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_TargetLock);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Stamina);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_BlockedBy_Stamina);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_SpecialWeaponAbility_Light);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_SpecialWeaponAbility_Heavy);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_PickUp_Items);

    //ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_SpecialWeaponAbility_Light);
    //ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_SpecialWeaponAbility_Heavy);


    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SuccessfulBlock);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Left);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Right);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_ActivateRolling);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_AOE);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_ConsumeItems);

    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rolling);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Blocking);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_TargetLock);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Stamina_Empty);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Stamina_Regen);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Stamina_Full);

    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);

    /** Enemy tags **/
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_SummonEnemies);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_SpawnItem);

    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_SummonEnemies);

    
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_UnderAttack);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Unbloackable);

    /** Shared tags **/
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);

    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_SpawnProjectile);

    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);

    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Front);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Left);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Right);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Back);
    ACTIONADVENTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Invincible);
}